[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/blizzard/*"
  to = "/.netlify/functions/blizzard-proxy/:splat"
  status = 200
  force = true